---
title: "Aggregation"
date: "11/2/2023"
output: html_document
---

```{r}
source("../Scripts/runMethods.R")
source("../Scripts/aggregation.R")
allints <- readRDS("../Scripts/allInteractors.rds")
```

```{r}
getResults <- function(datasets, methods=c("CVqt","ML","GCnorm:decoupleRlimmamlm"), ...){
  lapply(setNames(names(datasets),names(datasets)), FUN=function(x){
    print(x)
    res <- lapply(setNames(methods, methods), FUN=function(y){
      folder <- ifelse(grepl("GCnorm:",y), "GCnorm","fullFrags")
      y <- gsub("GCnorm:","",y,fixed=TRUE)
      p <- file.path("..",folder,x,"runATAC_results","with_pvalues",paste0(y,".rds"))
      # if(!file.exists(p)){
      #   folder <- "fullFrags"
      #   p <- file.path("..",folder,x,"runATAC_results","with_pvalues",paste0(y,".rds"))
      # }
      readRDS(p)
    })
    ag <- runAggregations(res, ...)
    truth <- x
    if(!is.null(datasets[[x]]$truth)) truth <- datasets[[x]]$truth
    out <- lapply(list(original=res, aggregated=ag), FUN=function(res){
      lapply(res, truth=truth, interactors=allints, FUN=.getBenchmarkMetrics)
    })
  })
}
```


```{r}
bml <- getResults(getDatasets())
bml2 <- dplyr::bind_rows(lapply(bml, FUN=function(x){
  dplyr::bind_rows(lapply(x, FUN=function(y) dplyr::bind_rows(y, .id="method")),
                   .id="type")
}), .id="dataset")
bml2$type <- factor(bml2$type, c("original","aggregated"), c("original methods", "aggregation methods"))
saveRDS(bml2, "aggregated.bm.rds")
```


```{r}
rankBreaks=c(1,6,20,50,100,200,400)
ggplot(bml2, aes(reorder(method,-sqrt(rank)), reorder(dataset, -sqrt(rank)), fill=sqrt(rank), label=rank)) + geom_tile() + 
  facet_wrap(~type, scales="free_x") + geom_text() + theme_minimal() +
  theme(legend.position="bottom", legend.key.width = unit(1,"cm"), panel.grid = element_blank(),
            axis.text.x=element_text(angle=45, hjust=1, vjust=1)) +
  scale_fill_viridis_c(direction=-1, breaks=sqrt(rankBreaks), 
                       trans="sqrt", labels=c("top",rankBreaks[-1])) +
  labs(x="", y="", fill="rank of \ntrue motif   ")
```

# MLM+CV score aggregation

```{r}
cv <- readRDS("../fullFrags/BANP/runATAC_results/raw/CV_raw.rds")$obj1
mlm <- readRDS("../GCnorm/BANP/runATAC_results/raw/decoupleRlimma_raw.rds")$res
mlm <- mlm[which(mlm$statistic=="mlm"),]
mlm <- reshape2::dcast(mlm, source~condition, value.var="score")
row.names(mlm) <- mlm[,1]
mlm <- as.matrix(mlm[,-1])

ints <- readRDS("../Scripts/allInteractors.rds")
ds <- getDatasets()
res <- lapply(setNames(names(ds),names(ds)), FUN=function(x){
  cv <- readRDS(paste0("../fullFrags/",x,"/runATAC_results/raw/CV_raw.rds"))$obj1
  mlm <- readRDS(paste0("../GCnorm/",x,"/runATAC_results/raw/decoupleRlimma_raw.rds"))$res
  mlm <- mlm[which(mlm$statistic=="mlm"),]
  mlm <- reshape2::dcast(mlm, source~condition, value.var="score")
  row.names(mlm) <- mlm[,1]
  mlm <- as.matrix(mlm[,-1])
  m <- t(t(scale(mlm))+t(scale(assays(cv)$z)))
  design <- rep(LETTERS[1:2], each=ncol(m)/2)
  fit <- eBayes(lmFit(m, model.matrix(~design)))
  res <- topTable(fit, number=Inf)
  res <- data.frame(row.names=row.names(res), logFC=res$logFC, t=res$t,
                    p=res$P.Value, padj=res$adj.P.Val)
  res <- res[order(res$p, -abs(res$logFC)),]
  res$rank <- seq_len(nrow(res))

  bm <- .getBenchmarkMetrics(res, ds[[x]]$truth, interactors = ints)
  list(res=res, bm=bm)
})

bm <- dplyr::bind_rows(lapply(res, FUN=function(x) x$bm), .id="dataset")
bm$method <- "(chromVAR+MLM)>limma"
saveRDS(bm, "MLM_CV.rds")
```

