---
title: "Dataset characterization"
author: "Pierre-Luc Germain"
date: "10/16/2023"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(edgeR)
  library(SummarizedExperiment)
  library(rtracklayer)
  library(GenomicRanges)
  library(Matrix)
  library(BiocParallel)
})
source("../Scripts/runMethods.R")
source("../Scripts/runVIPER.R") # for the DEA part
```

# Treatment effects

```{r, eval=FALSE}
lf <- list.files("../fullFrags", pattern="countmatrix", recursive=TRUE, full=TRUE)
names(lf) <- basename(dirname(dirname(dirname(lf))))
cms <- lapply(lf, FUN=readRDS)
das <- bplapply(cms, BPPARAM=MulticoreParam(4), FUN=function(x){
  g1 <- seq_len(ncol(x)/2)
  dATestedgeR(x[,g1], x[,-g1])[,c("logFC", "PValue", "FDR")]
})
das2 <- dplyr::bind_rows(das, .id="Dataset")
das2$Dataset <- factor(das2$Dataset)
saveRDS(das2, file="allDAres.rds")
```

```{r, include=FALSE}
das2 <- readRDS("allDAres.rds")
```

```{r}
nsig <- dplyr::bind_rows(lapply(das, FUN=function(x){
  data.frame(n=nrow(x), sig=sum(x$FDR<0.05,na.rm=TRUE),
             unadj=sum(x$PValue<0.05,na.rm=TRUE),
             unadjProp=sum(x$PValue<0.05,na.rm=TRUE)/nrow(x))
}), .id="Dataset")
nsig$label <- paste0("q<0.05: ", nsig$sig, "\np<0.05: ", round(100*nsig$unadjProp), "%")
ggplot(das2, aes(logFC, -log10(FDR))) + geom_hline(yintercept = -log10(0.05), linetype="dashed", colour="grey") + theme_bw() +
  ggrastr::geom_point_rast(size=0.5) + facet_wrap(~Dataset) + 
  geom_text(data=nsig, x=-4, y=max(sqrt(-log10(das2$FDR))), vjust=1, aes(label=label), size=3) + scale_y_sqrt()
```

# Motif overlap with peaks

```{r, eval=FALSE}
ds <- getDatasets()
chips <- list.files("ChIPpeaks", pattern="bed\\.gz$", full=TRUE)
peakr <- dplyr::bind_rows(lapply(setNames(names(ds), names(ds)), FUN=function(x){
  atac <- rtracklayer::import(list.files(file.path("..","fullFrags",x,"peaks"), full=TRUE))
  pmoi <- readRDS(file.path("..","fullFrags",x,"runATAC_results","others","pmoi.rds"))
  tmot <- ifelse(x=="NR3C1","GCR",x)
  pmoi <- pmoi[pmoi$motif_id==tmot]
  if(x=="ESR1") x <- "_ER_"
  chip <- chips[grep(x,chips)]
  if(length(chip)==0) return(NULL)
  chip <- tryCatch({
    rtracklayer::import(chip)
  }, error=function(e){
    import(chip, format="narrowPeak")
  })
  seqlevelsStyle(chip) <-
    ifelse(any(seqlevelsStyle(atac)=="Ensembl"),"ensembl","UCSC")
  chip$hasMotif <- overlapsAny(chip, pmoi)
  atac$hasMotif <- overlapsAny(atac, pmoi)
  atac$hasPeak <- overlapsAny(atac, chip)
  data.frame(
    ChIPpeaksWithMotif=sum(chip$hasMotif)/length(chip),
    atacWithMotif=sum(atac$hasMotif)/length(atac),
    atacChIP=sum(atac$hasPeak)/length(atac),
    atacChIPWithMotif=sum(atac$hasMotif & atac$hasPeak)/sum(atac$hasPeak),
    atacBgWithMotif=sum(atac$hasMotif & !atac$hasPeak)/sum(!atac$hasPeak),
    atacMotifWithChIP=sum(atac$hasPeak & atac$hasMotif)/sum(atac$hasMotif),
    atacPeakLog2EnrichmentWithinMotifs=log2(sum(atac$hasMotif & 
                    atac$hasPeak)/(sum(atac$hasMotif)*sum(atac$hasPeak)/length(atac))))
}), .id="Dataset")
saveRDS(peakr, "motifPeakData.rds")
```

```{r, include=FALSE}
peakr <- readRDS("motifPeakData.rds")
```

```{r, fig.width=5, fig.height=3}
ggplot(peakr, aes(Dataset, atacPeakLog2EnrichmentWithinMotifs)) + geom_col() + ylab("log2(enrichment) of ChIP peaks\nin motif-containing ATAC peaks") + theme_bw()
```

```{r}
m <- merge(peakr, nsig, by="Dataset")
res <- readRDS("../fullFrags/results.rds")
ag <- aggregate(res$rank, by=res[,"dataset",drop=FALSE], FUN=median)
row.names(ag) <- ag[,1]
m$medianRank <- ag[m$Dataset, 2]
m$log10sigProp <- log10((1+m$sig)/m$n)
ggplot(m, aes((1+sig)/n, medianRank, colour=atacPeakLog2EnrichmentWithinMotifs,
              label=Dataset)) + 
  geom_point(size=5) + ggrepel::geom_text_repel(min.segment.length=0) +
  scale_y_sqrt() + scale_x_log10() + theme_bw() +
  scale_colour_viridis_c() + 
  labs(x="Proportion of ATAC peaks with FDR<0.05",
       y="Median rank of true TF\nacross methods",
       colour="motif log2\nenrichment")
```

# Checkup on NR1H4

```{r}
ml <- readRDS("../fullFrags/RUNX2/runATAC_results/with_pvalues/CV.rds")
chip <- "ChIPpeaks/GSE149075_NR1H3_peaks_WT_GW.bed.gz"
```

