---
title: "Motif clustering"
output: html_document
date: "2024-06-05"
---

```{r}
suppressPackageStartupMessages({
  library(universalmotif)
  library(TFBSTools)
  library(bluster)
  library(igraph)
})
source("../Scripts/runMethods.R")
```

# mouse

```{r}
mo <- readRDS("../fullFrags/BANP/runATAC_results/others/motifs.rds")

cc <- universalmotif::compare_motifs(mo, nthreads = 10, score.strat = "wa.mean")
cc[is.na(cc)] <- 0
h <- as.dendrogram(hclust(as.dist(1-cc), method = "complete"))

cl <- lapply(cut(as.dendrogram(h), h=0.35)$lower, FUN=labels)

# knn <- bluster::makeSNNGraph(cc, k=7, type="number")
# set.seed(123)
# cl <- cluster_leiden(knn, resolution_parameter = 3, n_iterations = 10)
# cl <- split(row.names(cc), cl$membership)

names(cl) <- sapply(cl, FUN=paste, collapse="/")

merged <- lapply(cl, FUN=function(x){
  if(length(x)==1) return(mo[[x]])
  merge_motifs(mo[x])
})
# check the merge:
cc2 <- universalmotif::compare_motifs(merged, score.strat = "wa.mean")
ComplexHeatmap::Heatmap(cc2, show_row_names=FALSE, show_column_names=FALSE)

merged <- lapply(merged, FUN=function(x){
  if(x@strand=="*") x@strand <- "+-"
  convert_motifs(x)
})

saveRDS(merged, "mergedMotifs.mouse.rds")

topPerArch <- lapply(cl, FUN=function(x){
  x <- convert_motifs(mo[x])
  x[[head(order(-sapply(x, FUN=function(x) x@icscore)),1)]]
})

saveRDS(topPerArch, "topMotifPerArchetype.mouse.rds")
```

```{r}
mo2 <- c(merged, convert_motifs(mo))
cc <- universalmotif::compare_motifs(mo2, nthreads = 10, score.strat = "wa.mean")
cc[is.na(cc)] <- 0
cc2 <- cc[grep("/",rownames(cc)),grep("/",rownames(cc),invert=TRUE)]
cmax <- t(colMaxs(cc2))
row.names(cmax) <- "Max"
Heatmap(cc2, show_column_names = FALSE, show_row_names = FALSE, column_title="Motifs", row_title="Archetypes", name="WPearson") %v% 
  Heatmap(cmax, show_column_names = FALSE, heatmap_height = unit(0.4, "cm"))

cc3 <- cc2[,intersect(colnames(cc2),unique(unlist(lapply(getDatasets(), FUN=function(x) x$truth))))]
```


# human


```{r}
mo <- readRDS("../fullFrags/GATA1/runATAC_results/others/motifs.rds")
names(mo) <- sapply(mo, FUN=function(x) x@name)

cc <- universalmotif::compare_motifs(mo, nthreads = 10, score.strat = "wa.mean")
cc[is.na(cc)] <- 0

h <- hclust(as.dist(1-cc), method = "complete")
cl <- lapply(cut(as.dendrogram(h), h=0.45)$lower, FUN=labels)
names(cl) <- sapply(cl, FUN=paste, collapse="/")

merged <- lapply(cl, FUN=function(x){
  if(length(x)==1) return(mo[[x]])
  merge_motifs(mo[x])
})

# check the merge:
cc2 <- universalmotif::compare_motifs(merged, score.strat = "wa.mean")
cc2[is.na(cc2)] <- 0
ComplexHeatmap::Heatmap(cc2, show_row_names=FALSE, show_column_names=FALSE)

merged <- lapply(merged, FUN=function(x){
  if(x@strand=="*") x@strand <- "+-"
  convert_motifs(x)
})

saveRDS(merged, "mergedMotifs.human.rds")

topPerArch <- lapply(cl, FUN=function(x){
  x <- convert_motifs(mo[x])
  x[[head(order(-sapply(x, FUN=function(x) x@icscore)),1)]]
})

saveRDS(topPerArch, "topMotifPerArchetype.human.rds")
```

```{r}
sessionInfo()
```

