---
title: "Figure 1"
author: "Pierre-Luc Germain"
date: "10/19/2023"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(cowplot)
  library(ComplexHeatmap)
})
source("../Scripts/plot.R")
source("../Scripts/runMethods.R")
res <- readRDS("../fullFrags/results.rds")
res <- res[which(!(res$method %in% c("Ridge-lm", # redundant with lasso
                                     "GCsmooth>fastMLM>limma"))),] # show in a later step
<<<<<<< HEAD
# remove non-basic chromvar/monalisa variants
res <- res[!grepl("scale|center|deviations\\)>Qt>|fewer|smaller|spearman",res$method),]
res$relAUC[is.na(res$relAUC)] <- ifelse(is.na(res$rank[which(is.na(res$relAUC))]), NA, 0)
res$archRelAUC[is.na(res$archRelAUC)] <- ifelse(is.na(res$rank[which(is.na(res$archRelAUC))]), NA, 0)
```

```{r, fig.width=10, fig.height=10}
ro <- rev(getOrder(res))
co <- getOrder(res, columns=TRUE)
h1 <- rankHeatmap2(res, doDraw=FALSE, column_title="Rank of true TF", row_names_gp=gpar(fontsize=10), row_order=ro, column_order = co)
h2 <- suppressWarnings(relAUCplot2(res, row_order=ro, doDraw=FALSE,
                  column_title="Network score", column_order=co))
h3 <- suppressWarnings(relAUCplot2(res, row_order=ro, doDraw=FALSE, name="Archetype\nscore",
                                   column_title="Archetype score", val="archRelAUC",
                                   col="archRelAUC", column_order=co, hmcolors=viridisLite::inferno(100)))
h <- grid.grabExpr(draw(h1 + h2 + h3, merge=TRUE))

=======
```

```{r, fig.width=9, fig.height=10.5}
h1 <- rankHeatmap2(res, doDraw=FALSE, column_title="Rank of true TF", row_names_gp=gpar(fontsize=10))
h2 <- suppressWarnings(relAUCplot2(res, row_order=names(row_order(h1)), doDraw=FALSE,
                  column_title="Network score", column_order=names(column_order(h1))))
h <- grid.grabExpr(draw(h1 + h2, merge=TRUE))
>>>>>>> 6cf4ed468599a293fee62a6b4993532db75112a0
res2 <- filterMethods(res, rename=FALSE)
res2$method <- gsub(":","",res2$method)
rtplot <- runtimePlot2(res2) + 
  scale_x_continuous(breaks=c(5,60,180,360,600,1200),
                     minor_breaks=c(1,30,120,270,480,900,1500)) +
  coord_trans(x="sqrt", xlim=c(1,1400)) + theme(legend.position=c(0.75,0.2))
pr <- sensFDRplot(res2, useArch = TRUE) + 
  ggtitle("Top variant per method, at nominal p.adjust <= 0.5") +
  theme(plot.title=element_text(size=11),
        axis.title=element_text(size=10))
fig <- cowplot::plot_grid(
  h,
  plot_grid(pr, rtplot, labels=LETTERS[2:3], nrow=1, scale=0.95, rel_widths=c(4,3.5)),
  nrow=2, labels=c("A",NA), scale=c(0.95,1), rel_heights = c(7,3)
)
fig
```

```{r}
<<<<<<< HEAD
pdf("Figure1.pdf", width=10, height=10)
=======
pdf("Figure1.pdf", width=9, height=10.5)
>>>>>>> 6cf4ed468599a293fee62a6b4993532db75112a0
fig
dev.off()
```

