---
title: "Summary figure"
output:
  html_document: default
  pdf_document: default
---

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(data.table)
  library(patchwork)
  library(RColorBrewer)
  library(viridis)
})
source("../Scripts/plot.R")
```

```{r, top methods}
# the top 5 performant on simulated and real data (one per family)
topMethods <- c("monaLisa.vsOthers", # real data / sim data
                "chromVAR(z)>Qt>limma",
                "diffTF(analytic)",
                "decoupleR(mlm)>limma",
                "MEIRLOP", 
                "msVIPER(binary)", # simulated data
                "chromVAR(z)>limma",
                "decoupleR(consensus)>limma",
                "ulm+GC")
```

```{r}
# results real datasets
resReal <- as.data.table(readRDS("../fullFrags/results.rds"))
resReal[,sig:=trueQ<=0.05]
resReal[,FDR:=fifelse(is.na(FDR), 0, FDR)]
resReal[,precision:=1-FDR]

# results simulated datasets
resSim <- as.data.table(readRDS("../simulations/res_all_effect_strength.rds"))

resSim[,c("tf", "paradigm", "es"):=tstrsplit(dataset, split="_", keep=1:3, 
                                             type.convert=TRUE)]
resSim <- subset(resSim, es>0)
resSim$method <- renameMethods(resSim$method)
resSim[,method:=fifelse(grepl("diffTF", method), "diffTF(analytic)", method)]
resSim[,sig:=trueQ<=0.05]
resSim[,FDR:=fifelse(is.na(FDR), 0, FDR)]

# minimal effect strength at which true TF is found
suppressWarnings(resSumSim <- resSim[,.(min_es_sig=min(es[sig]),
                                        sig=sum(sig)>0), 
                                     by=.(paradigm, tf, method)])
resSumSim[,es:=fifelse(!is.finite(min_es_sig), 1, min_es_sig)]
resSumSim <- merge(resSumSim, 
                   resSim[,c("paradigm", "tf", "method", "es", "FDR")], 
                   by.x=c("paradigm","tf","method", "es"),
                   by.y=c("paradigm", "tf", "method", "es"), 
                   all.x=TRUE, 
                   all.y=FALSE)

resSumSim[,precision:=1-FDR]
resSumSim[,dataset:=paste(tf, paradigm)]
resSumSim <- subset(resSumSim, method %in% topMethods)

resReal <- subset(resReal, method %in% unique(resSumSim$method))

# sensitivity plots

# ordering real datasets
resRealOrder <- resReal[,.(n_sig=sum(sig)), by=dataset]
resReal$dataset <- factor(resReal$dataset,
                          levels=resRealOrder$dataset[order(-resRealOrder$n_sig)], 
                          ordered=TRUE)

# ordering simulated datasets
resSimOrder <- resSumSim[,.(n_sig=sum(sig, na.rm=TRUE)), by=dataset]
resSumSim$dataset <- factor(resSumSim$dataset,
                            levels=resSimOrder$dataset[order(-resSimOrder$n_sig)], 
                            ordered=TRUE)

# ordering methods
orderMethods <- rbind(resReal[,.(n_sig=sum(sig)), by=method],
                      resSumSim[,.(n_sig=sum(sig)), by=method])
orderMethods <- orderMethods[,.(n_sig=sum(n_sig)), by=method]
resReal$method <- factor(resReal$method,
                         levels=orderMethods$method[order(orderMethods$n_sig)],
                         ordered=TRUE)
resSumSim$method <- factor(resSumSim$method,
                         levels=orderMethods$method[order(orderMethods$n_sig)],
                         ordered=TRUE)

# real dataset summary plot
realRank <- ggplot(resReal, aes(x=dataset, y=method, color=sqrt(rank))) +
  geom_point(aes(size=sig)) + 
  # geom_text(aes(label=rank), colour="white", alpha=0.5, size=3) + 
  scale_size_manual(values=c(4,9), name="Detected (FDR<0.05)") +
  scale_color_gradientn(trans = "sqrt",
                        breaks=c(500,200,100,50,10,1),
                        colours=inferno(50), 
                        name="Rank of true TF")+  
  #scale_x_discrete(guide = guide_axis(n.dodge=2))+
  ggtitle("Real datasets")+
  guides(colour = guide_colourbar(title.position="top", barwidth=unit(3.5,"cm")),
         size = guide_legend(title.position="top")) +
  theme_bw()+
  theme(legend.position="top",
        axis.text.y = element_text(size=12, color="black"),
        axis.text.x = element_text(angle=90, hjust = 1, vjust=0.5),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.tag=element_text(face="bold", size=18))

# simulated summary plot
resSumSim[,min_es_sig:=fifelse(!is.finite(min_es_sig), 
                               as.numeric(NA), min_es_sig)]
resSumSim$dataset2 <- resSumSim$dataset
levels(resSumSim$dataset2) <- gsub("activation","activ.",
                                   gsub("haploinsufficiency","haplo.",
                                        gsub(" ","\n",levels(resSumSim$dataset))))
resSumSim[,min_es_sig:=fifelse(is.na(min_es_sig), "not detected", 
                               as.character(min_es_sig))]
colors <- c(rev(brewer.pal(4,"Purples")), "darkgrey")
names(colors) <- c("0.25", "0.5", "1", "3", "not detected")
esSens <- ggplot(resSumSim, aes(x=dataset2, y=method, color=min_es_sig))+
  geom_point(aes(size=sig))+
  scale_size_manual(values=c(4,9), guide="none")+
  #scale_x_discrete(guide = guide_axis(n.dodge=2))+
  scale_color_manual(values=colors, name="Minimal pertubation strength for detection")+
  ggtitle("Simulated datasets")+
  guides(colour=guide_legend(override.aes = list(size=8, alpha=1, linewidth=3),
                             title.position="top"))+
  theme_bw()+
  theme(legend.position="top",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(), 
        axis.ticks.y=element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle=90, hjust = 1, vjust=0.5),
        plot.tag=element_blank(),
        axis.ticks.x=element_blank())
```


```{r}
# precision plot & overall sensitivity/specificity
res1 <- readRDS("../fullFrags/results.rds")
res2 <- as.data.table(readRDS("../simulations/res_all_effect_strength.rds"))
res2[,c("tf", "paradigm", "es"):=tstrsplit(dataset, split="_", keep=1:3, 
                                             type.convert=TRUE)]
res2 <- subset(resSim, es>0)

res2 <- renameMethods(as.data.frame(res2))
res2 <- as.data.table(res2)
res2[,method:=fifelse(grepl("diffTF", method), "diffTF(analytic)", method)]
res2 <- subset(res2, method %in% topMethods)
res2 <- as.data.frame(res2)
res1 <- res1[which(res1$method %in% res2$method),]

i <- intersect(colnames(res1),colnames(res2))
res <- rbind(res1[,i], res2[,i])
res$FDR[which(is.na(res$FDR))] <- 0

ag <- aggregate(1-res$FDR, by=list(method=res$method), FUN=mean)
ag$method <- factor(ag$method, levels = levels(resSumSim$method))
prec <- ggplot(ag, aes(x, method)) + 
  geom_col(fill=rev(RColorBrewer::brewer.pal(9, "Purples"))[1]) + theme_bw() +
          ggtitle("Average precision") +
          theme(axis.title.y = element_blank(), axis.title.x = element_blank(),
                axis.text.y = element_blank(), axis.ticks.y = element_blank())

pr <- sensFDRplot(res, label.size=4) + labs(tags="B", y="Precision") +
  theme( plot.tag=element_text(face="bold", size=18),
         axis.title=element_text(size=13) )
```

```{r, fig.width=8, fig.height=18}
design <- "
11111222233
44445555555
"

pdf("Summary.pdf", width=12, height=7)
realRank + labs(tags="A") + (esSens + theme(axis.text.x = element_text())) + prec + 
  guide_area() + free(pr) + plot_layout(guides="collect", design=design)
dev.off()
```
