---
title: "04_fld"
author: "Emanuel Sonder"
date: "06 11 2023"
output: html_document
---

```{r setup}
library(Rsamtools)
library(BiocParallel)
library(GenomicAlignments)
library(regioneR)
library(BSgenome.Hsapiens.UCSC.hg38)
library(MASS)
library(mclust)
library(Repitools)
library(data.table)

data.table::setDTthreads(2)
source("./scripts/atacSignalSimulation.R")
source("../Scripts/runMethods.R")
source("../Scripts/compileBenchmark.R")
```

```{r, paths}
outDir <- "./data/sim_data_fld"
bedBaseDir <- "./data/ATAC_beds"
atacPeaksPath <- "./data/peaks/merged_peaks.narrowPeak"
haploPath <- "./data/haploinsufficiency.rds"
actPath <- "./data/activation.rds"

# Baseline samples 
bedPaths <- paste(bedBaseDir, c("ENCFF495DQP.rds", "ENCFF130DND.rds", 
                                "ENCFF447ZRG.rds", "ENCFF966ELR.rds",
                                "ENCFF358GWK.rds", "ENCFF963YZH.rds"), sep="/")

# ChIP-peaks
znf143PeaksDir <- "./data/ChIP_peaks/ENCFF500EWB_ZNF143.bed.gz"
mazPeaksDir <- "./data/ChIP_peaks/ENCFF250FJC_MAZ.bed.gz"
cebpbPeaksDir <- "./data/ChIP_peaks/ENCFF156OCY_CEBPB.bed.gz"
ctcfPeaksDir <- "./data/ChIP_peaks/ENCFF592UDD_CTCF.bed.gz"
```

# FLD

```{r, eval=FALSE}
frags <- readRDS("./data/ATAC_beds/ENCFF495DQP.rds")
wDt <- as.data.table(frags)

wDt[,cluster:=as.numeric(cut(width, breaks=c(0,120,300,500), include.lowest=TRUE))]
wDt[,.N/nrow(wDt), by=cluster]
```

# Simulate 

Define simulation parameters
```{r, simulation parameters}
simParams <- as.data.table(expand.grid(es=c(0, 1, 3),
                                       tf=c("CTCF"),
                                       paradigm=c("activation", 
                                                  "haploinsufficiency"),
                                       fld_setting=c("nf_enriched",
                                                     "mono_enriched",
                                                     "group")))

# nf_enriched: 0.5, 0.35, 0.13,0.02
# mono_enriched: 0.35,0.5,0.13,0.02

# add varying of ATAC-peaks parameter in case of activation es: 0.5,1,3
#simParams[,vary_atac_peaks:=fifelse(paradigm=="activation" & es>0, TRUE, FALSE)] #09.12.24
simParams[,vary_atac_peaks:=FALSE]
simParams[,peaks_path:=fifelse(tf=="ZNF143", znf143PeaksDir, "")]
simParams[,peaks_path:=fifelse(tf=="MAZ", mazPeaksDir, peaks_path)]
simParams[,peaks_path:=fifelse(tf=="CEBPB", cebpbPeaksDir, peaks_path)]
simParams[,peaks_path:=fifelse(tf=="CTCF", ctcfPeaksDir, peaks_path)]

simParams[,paradigm_path:=fifelse(paradigm=="activation", actPath, haploPath)]

# Fixed parameters
sampleNames <- c("group1_1", "group1_2", "group1_3",
                 "group2_1", "group2_2", "group2_3")
design <- c(1,1,1,-1,-1,-1)
genome <- BSgenome.Hsapiens.UCSC.hg38
which <- GRanges(Rle(paste0("chr", 1:22)), IRanges(start=1, width=536870912))


# here FLD & GC parameters will be the same across groups 
paramsGroup1 <- paramsGroup2 <- data.table()
paramsGroup1$name <- "group1"
paramsGroup2$name <- "group2"
```

Simulate
```{r, simulate, eval=FALSE}
# run sequentially 
lapply(1:nrow(simParams), function(i){
  
  if(simParams[i,]$fld_setting=="nf_enriched")
  {

    paramsGroup1$prob_nf <- paramsGroup2$prob_nf <- 0.5
    paramsGroup1$prob_mono <- paramsGroup2$prob_mono <- 0.35
    paramsGroup1$prob_di <- paramsGroup2$prob_di <- 0.13
    paramsGroup1$prob_tri <- paramsGroup2$prob_tri <- 0.02
   
    paramsGroup1$estimateProb <- paramsGroup2$estimateProb <- FALSE
  }
  else if(simParams[i,]$fld_setting=="mono_enriched"){
    
    paramsGroup1$prob_nf <- paramsGroup2$prob_nf <- 0.35
    paramsGroup1$prob_mono <- paramsGroup2$prob_mono <- 0.5
    paramsGroup1$prob_di <- paramsGroup2$prob_di <- 0.13
    paramsGroup1$prob_tri <- paramsGroup2$prob_tri <- 0.02
    
    paramsGroup1$estimateProb <- paramsGroup2$estimateProb <- FALSE
  }
  else if(simParams[i,]$fld_setting=="group")
  {
    paramsGroup1$prob_nf <- 0.5
    paramsGroup1$prob_mono <- 0.35
    paramsGroup1$prob_di <- 0.13
    paramsGroup1$prob_tri <- 0.02
    
    paramsGroup2$prob_nf <- 0.35
    paramsGroup2$prob_mono <- 0.5
    paramsGroup2$prob_di <- 0.13
    paramsGroup2$prob_tri <- 0.02
  
    paramsGroup1$estimateProb <- paramsGroup2$estimateProb <- FALSE
  }
  
  lfcDist <- readRDS(simParams[i,]$paradigm_path)
  simData <- simAtacData(bamPaths=bedPaths,
                          chIPPeakDir=simParams[i,]$peaks_path,
                          atacPeakDir=atacPeaksPath,
                          sampleNames=sampleNames,
                          effectStrength=simParams[i,]$es,
                          gcBiases=NULL,
                          fracSub=1,
                          design=design,
                          paramsGroup1=paramsGroup1,
                          paramsGroup2=paramsGroup2,
                          lfcDist=lfcDist,
                          which=which,
                          genome=genome,
                          simGCBias=FALSE,
                          simFLD=TRUE,
                          varyAtacPeaks=simParams[i,]$vary_atac_peaks,
                          colNamesChIPPeaks=c("chr","start", "end",
                                              "name", "score", "strand",
                                             "signalValue", "pValue",
                                             "qValue", "peak"),
                         colNamesAtacPeaks=c("chr","start", "end",
                                             "name", "score", "strand",
                                             "signalValue", "pValue",
                                             "qValue", "peak"),
                         enrColChIPName="signalValue",
                         enrColAtacName="signalValue",
                         lfcCol="lfc",
                         annotationStyle="UCSC",
                         maxReadPerPeak=1e6,
                         equalLib=FALSE,
                         seed=42)
  
  folderName <- paste(simParams[i,]$tf, simParams[i,]$paradigm, 
                      simParams[i,]$es, simParams[i,]$vary_atac_peaks,
                      simParams[i,]$fld_setting, sep="_")
  folderName <- paste(folderName, "seq_files", sep="/")
  saveToBed(simData, outDir, folderName, saveMerged=FALSE)
  
  wd <- getwd()
  setwd(file.path(outDir, folderName))
  mergeBedsCommand <- "cat -u group1_1.bed group1_2.bed group1_3.bed > group1_merged.bed"
  system(mergeBedsCommand)
  mergeBedsCommand <- "cat -u group2_1.bed group2_2.bed group2_3.bed > group2_merged.bed"
  system(mergeBedsCommand)
  
  callPeaksCommand <- "nice -n 3 macs2 callpeak --outdir ../peaks -f BEDPE -n group1 -t group1_merged.bed"
  system(callPeaksCommand)
  
  callPeaksCommand <- "nice -n 3 macs2 callpeak --outdir ../peaks -f BEDPE -n group2 -t group2_merged.bed"
  system(callPeaksCommand)
  
  file.remove("group1_merged.bed")
  file.remove("group2_merged.bed")
  
  # merge peaks 
  #dir.create("../peaks")
  mergePeaksCommand <- "cat ../peaks/*narrowPeak | cut -f1-3 | sort -k1,1 -k2,2n | bedtools merge -i - > ../peaks/merged_peaks.bed"
  system(mergePeaksCommand)
  
  # Filter to non-sex chromosomes
  # peaks <- fread("../peaks/merged_peaks.narrowPeak")
  # peaks <- subset(peaks, V1 %in% paste0("chr", 1:22))
  # write.table(peaks,
  #             "../peaks/sub_merged_peaks.narrowPeak",
  #             quote=FALSE, col.names=FALSE,
  #             sep="\t",
  #             row.names=FALSE)

  setwd(wd)
  gc()
})
```

# Benchmark 

Run methods
```{r, run methods, eval=TRUE}
simParams[,folderName:=paste(tf, paradigm, es, vary_atac_peaks, fld_setting, sep="_")]
subSimParams <- simParams

datasets <- lapply(1:nrow(subSimParams), function(i){
  ds <- list(truth=subSimParams[i,]$tf,
             species="h", 
             type="sim",
             seqStyle="UCSC",
             peakFile="./peaks/merged_peaks.bed",
             folder=paste0("./data/sim_data_fld/", subSimParams[i,]$folderName),
             readType="bed")
  return(ds)
})
names(datasets) <- subSimParams$folderName

runAll(datasets, scriptsFolder="../../../../Scripts", 
       methods=c("fastMLM","chromVAR", "minaLisa.others", "monaLisa.zero", "StabSel"), # "chromVAR", "minaLisa.others", "monaLisa.zero", "StabSel"
       forceRerun=TRUE)

```

# Sessioninfo 

```{r}
print(sessionInfo())
```
