---
title: "01_effect_strength"
author: "Emanuel Sonder"
date: "06 11 2023"
output: html_document
---

```{r setup}
library(ggplot2)
library(cowplot)
library(ComplexHeatmap)
library(data.table)
library(SummarizedExperiment)
library(patchwork)
library(RColorBrewer)
library(ggpointdensity)
library(viridis)
library(ggrepel)
library(patchwork)
library(limma)
library(ggh4x)
library(ggpubr)
library(ggimage)
library(stringr)
library(BSgenome.Hsapiens.UCSC.hg38)
library(png)

BSgenome <- BSgenome.Hsapiens.UCSC.hg38

source("../Scripts/plot.R")
source("../Scripts/runMethods.R")
source("../Scripts/compileBenchmark.R")
source("../Scripts/getpmoi.R")
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", 
                "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r, peak ranges}
peakZNF143Ranges <- fread("./data/ChIP_peaks/ENCFF500EWB_ZNF143.bed.gz", 
                    select=1:3, col.names=c("chr", "start", "end"))
peakZNF143Ranges <- makeGRangesFromDataFrame(as.data.frame(peakZNF143Ranges))
peakMAZRanges <- fread("./data/ChIP_peaks/ENCFF250FJC_MAZ.bed.gz", 
                    select=1:3, col.names=c("chr", "start", "end"))
peakMAZRanges <- makeGRangesFromDataFrame(as.data.frame(peakMAZRanges))
peakCEBPBRanges <- fread("./data/ChIP_peaks/ENCFF156OCY_CEBPB.bed.gz", 
                    select=1:3, col.names=c("chr", "start", "end"))
peakCEBPBRanges <- makeGRangesFromDataFrame(as.data.frame(peakCEBPBRanges))
peakCTCFRanges <- fread("./data/ChIP_peaks/ENCFF592UDD_CTCF.bed.gz", 
                    select=1:3, col.names=c("chr", "start", "end"))
peakCTCFRanges <- makeGRangesFromDataFrame(as.data.frame(peakCTCFRanges))
```

Rank plots Enrichment - simulated data
```{r}
freqAll <- readRDS("freqAll.rds")  

# Calculate enrichment
freqAll[,prop_chIP:=n_chIP_motif/tot_chIP]
freqAll[,prop_ATAC:=n_atac_only_motif/tot_atac]
freqAll[,enr:=prop_chIP/prop_ATAC]
freqAll[,prop:=n_chIP_motif/n_atac_motif_total]

freqAll[,prop_co_peak:=n_co_peak/n_atac_motif_total]
freqAll[,prop_co_peak_chip:=n_co_peak_chip/n_chIP_motif]

freqAll[,rank:=frank(enr), by=.(tf, paradigm)]
freqAll[,percentile:=rank/.N, by=.(tf, paradigm)]

# get motif GC content
motifs <- getNonRedundantMotifs(format="universal", species=c("Hsapiens"))
motSeq <- lapply(motifs, function(m)m@consensus)
motSeq <- data.table(seq=unlist(motSeq), motif_id=names(motSeq))
motSeq[,GC_content:=(str_count(seq, "GC")*2)/nchar(seq)]
freqAll <- merge(freqAll, motSeq, by="motif_id", all.x=TRUE)

# get top enriched tfs
freqTrueDt <- subset(freqAll, tf==motif_id)
freqMax <- subset(freqAll, rank==1)
freqTrueDt <- merge(freqTrueDt, freqMax, 
                    by=c("paradigm", "tf", "es"), suffixes=c("", ".y"))
freqTrueDt[,enr_diff:=enr-enr.y]
freqTrueDt <- freqTrueDt[,c("enr", "rank", "enr_diff", "tf", "paradigm", 
                            "es", "percentile", "prop",
                            "prop_co_peak", "prop_co_peak_chip", "GC_content")]
freqTop <- subset(freqAll, rank<=3)

# Rename ZN143
freqAll[,tf:=fifelse(tf=="ZN143", "ZNF143", tf)]
freqTrueDt[,tf:=fifelse(tf=="ZN143", "ZNF143", tf)]
freqTop[,tf:=fifelse(tf=="ZN143", "ZNF143", tf)]

coRankSim <- ggplot(subset(freqAll, paradigm=="activation"), aes(x=percentile, y=enr))+
  geom_label_repel(subset(freqTop, paradigm=="activation" & motif_id!="CTCF"), 
             mapping=aes(x=percentile, y=enr, label=motif_id), 
             alpha=1, color="grey", nudge_x=-0.3, nudge_y=0.3)+
  geom_label_repel(subset(freqTrueDt, paradigm=="activation"), 
             mapping=aes(x=percentile, y=enr, label=tf), 
             alpha=1, color="black", nudge_x=-0.3, nudge_y=0.1,  direction="x")+
  geom_point(aes(color=prop_co_peak))+
  geom_point(subset(freqTrueDt, paradigm=="activation"), 
             mapping=aes(color=prop_co_peak), size=2)+
  scale_color_gradientn(trans = "sqrt",
                        breaks=c(1.0,0.75,0.5,0.25,0.1,0),
                        colours=viridis(length(unique(freqAll$prop_co_peak))), 
                        name="Proportion of matches co-occuring with true motif")+
  facet_grid(cols=vars(tf))+
  ylab("Enrichment of motif in ChIP-peaks")+
  xlab("Percentile")+
  labs(tag="C")+
  theme_bw()+
  theme(legend.box.just="left",
        legend.position="bottom", 
        legend.spacing.x=unit(0.5, 'cm'),
        legend.key.width = unit(1, "cm"))
coRankSim

coRankGC <- ggplot(subset(freqAll, paradigm=="activation"), aes(x=percentile, y=enr))+
  geom_label_repel(subset(freqTop, paradigm=="activation" & motif_id!="CTCF"), 
             mapping=aes(x=percentile, y=enr, label=motif_id), 
             alpha=1, color="grey", nudge_x=-0.3, nudge_y=0.3)+
  geom_label_repel(subset(freqTrueDt, paradigm=="activation"), 
             mapping=aes(x=percentile, y=enr, label=tf), 
             alpha=1, color="black", nudge_x=-0.3, nudge_y=0.1,  direction="x")+
  geom_point(aes(color=GC_content))+
  geom_point(subset(freqTrueDt, paradigm=="activation"), 
             mapping=aes(color=GC_content), size=2)+
  scale_color_gradientn(trans = "sqrt",
                        breaks=c(1.0,0.8,0.75,0.6,0.4,0.25,0.1,0),
                        colours=inferno(length(unique(freqAll$GC_content))), 
                        name="GC content")+
  facet_grid(cols=vars(tf))+
  ylab("Enrichment of motif in ChIP-peaks")+
  xlab("Percentile")+
  scale_size(range=c(0,1))+
  labs(tag="D")+
  theme_bw()+
  theme(legend.box.just = "left", 
        legend.margin = margin(l=0),
        legend.position="bottom", 
        legend.spacing.x=unit(0.5, 'cm'),
        legend.key.width = unit(1, "cm"))

rankSim <- coRankSim / coRankGC 

# get gc content of peaks
gcPeakCEBPB <- Repitools::gcContentCalc(peakCEBPBRanges, BSgenome)
gcPeakCTCF <- Repitools::gcContentCalc(peakCTCFRanges, BSgenome)
gcPeakMAZ <- Repitools::gcContentCalc(peakMAZRanges, BSgenome)
gcPeakZNF143 <- Repitools::gcContentCalc(peakZNF143Ranges, BSgenome)
peakGC <- data.table(tf=c(rep("CEBPB", length(gcPeakCEBPB)),
                          rep("CTCF", length(gcPeakCTCF)),
                          rep("MAZ", length(gcPeakMAZ)),
                          rep("ZNF143", length(gcPeakZNF143))),
                     gc_content=c(gcPeakCEBPB, gcPeakCTCF, 
                                  gcPeakMAZ, gcPeakZNF143))

peakGCPlot <- ggplot(peakGC, aes(x=gc_content, color=tf, fill=tf))+
geom_density(alpha=0.7)+
scale_color_manual(values=cbbPalette)+
scale_fill_manual(values=cbbPalette)+
facet_grid(cols=vars(tf))+
geom_vline(xintercept=0.5, linetype="dashed")+
guides(fill = guide_legend(title="Transcription Factor"))+
guides(color="none")+
xlab("GC content ChIP-peaks")+
labs(tag="E")+
theme_bw()+
theme(legend.position="none",
      legend.margin=margin(l=0, r=0, t=0, b=0))
peakGCPlot

simRanks <- coRankSim / coRankGC / peakGCPlot & theme(legend.justification = "left")
ggsave("simEnrGCRanks.png", simRanks, units="cm", width=40, height=30)
```
# Count distributions

```{r, peak counts, error=TRUE}
countMats <- readRDS("countMats.rds")

countPlot <- ggplot(countMats, aes(x=log2(count), color=sample))+
geom_density()+
facet_nested(paradigm+tf~es)+
scale_color_manual(values=c(brewer.pal(5, "Reds")[3:5], brewer.pal(5, "Blues")[3:5]))+
labs(tag="A")+
theme_bw()

countPlot
ggsave("counts.png", units="cm", width=15, height=25)
```


MA plots
```{r}
countMats[,mean_group:=mean(count), 
          by=c("peak_id", "tf", "paradigm", "es", "varied_atac", "group")]
countMats[,mean_group1:=fifelse(group=="group1", mean_group, as.numeric(NA))]
countMats[,mean_group2:=fifelse(group=="group2", mean_group, as.numeric(NA))]

meanCounts <- countMats[,.(var=var(count),
                           mean=mean(count),
                           logFC=log2(max(mean_group1, na.rm=TRUE)/max(mean_group2, na.rm=TRUE)),
                           overlaps_motif=unique(overlaps_motif),
                           overlaps_chip=unique(overlaps_chip)), 
                        by=c("peak_id", "tf", "paradigm", "es", "varied_atac")]

meanCounts <- meanCounts[,.SD[sample(peak_id, 1.2e5)], by=.(paradigm, es, tf)]
```

```{r}
colsChIP <- c(cbbPalette[2], cbbPalette[3])
names(colsChIP) <- c("no overlap", "overlaps ChIP-peak")
meanCounts$overlaps_chip <- factor(meanCounts$overlaps_chip, 
                                  levels=c("no overlap", "overlaps ChIP-peak"),
                                    ordered=TRUE)

colsMotif <- c(cbbPalette[5], cbbPalette[4])
names(colsMotif) <- c("no overlap", "overlaps motif")
meanCounts$overlaps_motif <- factor(meanCounts$overlaps_motif, 
                                    levels=c("no overlap", "overlaps motif"),
                                    ordered=TRUE)
meanPointsMotif <- meanCounts[, .(mean_access=mean(mean),
                                  mean_lfc=mean(logFC[is.finite(logFC)], na.rm=TRUE)), 
                              by=.(paradigm,es,tf,overlaps_motif)]
meanPointsChIP <- meanCounts[, .(mean_access=mean(mean),
                                  mean_lfc=mean(logFC[is.finite(logFC)], na.rm=TRUE)), 
                             by=.(paradigm,es,tf,overlaps_chip)]


ovMotif <- ggplot(meanCounts, aes(x=log10(mean), y=logFC, color=overlaps_motif))+
  facet_nested(paradigm ~ tf + es, scales="free")+
  #geom_point(size=0.25, alpha=0.3)+
  #geom_density2d(linewidth=0.25, size=0.5)+
  #geom_point(subset(meanCounts, overlaps_motif=="no overlap"), 
  #           mapping=aes(x=log10(mean), y=logFC, color=overlaps_motif), size=0.25, alpha=0.3)+
  #geom_density2d(subset(meanCounts, overlaps_motif=="overlaps motif"),
  #               mapping=aes(x=log10(mean), y=logFC, color=overlaps_motif),linewidth=0.25, size=0.5)+
  geom_density2d(size=0.5)+
  geom_point(data=meanPointsMotif, mapping=aes(x=log10(mean_access), y=mean_lfc, color=overlaps_motif), size=3)+
  #geom_point(data=meanPointsMotif, aes(x=log10(mean_access), y=mean_lfc, color=overlaps_motif), size=3)+
  #geom_point(size=0.5, alpha=0.3)+
  geom_hline(yintercept=2, linetype="dashed")+
  geom_hline(yintercept=0)+
  geom_vline(xintercept=1.5, linetype="dotted")+
  geom_hline(yintercept=-2, linetype="dashed")+
  scale_color_manual(values=colsMotif, name="overlaps ChIP-peak:")+
  guides(colour = guide_legend(override.aes = list(size=3, alpha=1, linewidth=3)), title="")+
  xlab("log10(Mean Accessibility)")+
  theme_bw()+
  theme(legend.position="bottom",
         axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust = 0.5))
ovMotif

ovChIP <- ggplot(meanCounts, aes(x=log10(mean), y=logFC, color=overlaps_chip))+
  facet_nested(paradigm ~ tf + es)+
  geom_density2d(size=0.5)+
  geom_point(data=meanPointsChIP, mapping=aes(x=log10(mean_access), y=mean_lfc, color=overlaps_chip), size=3)+
  #geom_point(size=0.5, alpha=0.3)+
  geom_hline(yintercept=2, linetype="dashed")+
  geom_hline(yintercept=0)+
  geom_vline(xintercept=1.5, linetype="dotted")+
  geom_hline(yintercept=-2, linetype="dashed")+
  scale_color_manual(values=colsChIP, name="overlaps motif:")+
  xlab("log10(Mean Accessibility)")+
  guides(colour = guide_legend(override.aes = list(size=3, alpha=1, linewidth=3)), title="")+
  theme_bw()+
  theme(legend.position="bottom",
        axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust = 0.5))

ovPlot <- ovChIP / ovMotif
ggsave("sim_s4.png", units="cm", width=35, height=20)
```

Mean count vs variance (stratified by effect strength & paradigm)
```{r}
meanVarPlot <- ggplot(meanCounts, aes(x=log10(mean), y=log10(var)))+
               facet_nested(paradigm+tf~es)+
               xlab("Log10(mean count")+
               ylab("Log10(var)")+
               geom_pointdensity(size=0.5)+
               labs(tag="B")+
               theme_bw()
meanVarPlot
ggsave("meanVar.png", units="cm", width=15, height=25)
```

```{r}
(countPlot / meanVarPlot ) + 
  plot_annotation(tag_levels=list(c("A", "B"))) &
  theme(plot.tag = element_text(face="bold", size=18),
        axis.title=element_text(size=16),
        legend.title=element_text(size=16),
        axis.text=element_text(size=12),
        legend.text=element_text(size=12))
ggsave("sim_s3.png", units="cm", width=45, height=50)
```


Motif Enrichment & accessibility
accessibility colored by motif, chip, motif & chip by factor 
```{r, error=TRUE}
ggplot(countMats, aes(x=log10(count), color=overlaps_chip, linetype=group))+
geom_density()+
facet_nested(es~paradigm+tf)+
scale_color_manual(values=cbbPalette)+
theme_bw()
ggsave("countDensityChIP.png", units="cm", width=30, height=20)


ggplot(countMats, aes(x=log10(count), color=overlaps_motif, linetype=group))+
geom_density()+
facet_nested(es~paradigm+tf)+
scale_color_manual(values=cbbPalette)+
theme_bw()
ggsave("countDensityMotif.png", units="cm", width=30, height=20)
```

Motif proportion in ChIP peaks
```{r, error=TRUE}
peakZNF143Ranges <- fread("./data/ChIP_peaks/ENCFF500EWB_ZNF143.bed.gz")
peakZNF143MotifRanges <- fread("./data/ChIP_peaks/motif_ZN143.bed")

peakMAZRanges <- fread("./data/ChIP_peaks/ENCFF250FJC_MAZ.bed.gz")
peakMAZMotifRanges <- fread("./data/ChIP_peaks/motif_MAZ.bed")

peakCEBPBRanges <- fread("./data/ChIP_peaks/ENCFF156OCY_CEBPB.bed.gz")
peakCEBPBMotifRanges <- fread("./data/ChIP_peaks/motif_CEBPB.bed")

peakCTCFRanges <- fread("./data/ChIP_peaks/ENCFF592UDD_CTCF.bed.gz")
peakCTCFMotifRanges <- fread("./data/ChIP_peaks/motif_CTCF.bed")

propDt <- data.table(motif_prop=c(nrow(peakZNF143MotifRanges)/nrow(peakZNF143Ranges),
                                  nrow(peakMAZMotifRanges)/nrow(peakMAZRanges),
                                  nrow(peakCEBPBMotifRanges)/nrow(peakCEBPBRanges),
                                  nrow(peakCTCFMotifRanges)/nrow(peakCTCFRanges)), 
                    n_peaks=c(nrow(peakZNF143Ranges), nrow(peakMAZRanges),
                              nrow(peakCEBPBRanges), nrow(peakCTCFRanges)),
                    tf=c("ZNF143", "MAZ", "CEBPB", "CTCF"))

ggplot(propDt, aes(x=tf, y="enrichment", fill=motif_prop))+
geom_tile()+
geom_text(aes(label=round(motif_prop, 2), color=motif_prop))+
scale_fill_viridis(option="D")+
scale_color_gradient2(low = viridis(4)[5],
                      mid = viridis(4)[3],
                      high = viridis(4)[1])+
ylab("")+
ggtitle("Proportion in all ChIP-peaks")+
theme_minimal()

enrDt <- countMats[,.(motif_prop_chip=sum(overlaps_motif=="overlaps motif" & overlaps_chip=="overlaps ChIP")/sum(overlaps_chip=="overlaps ChIP"),
                      motif_prop_atac=sum(overlaps_motif=="overlaps motif")/.N,
                      n_chip_motif=sum(overlaps_motif=="overlaps motif" & overlaps_chip=="overlaps ChIP"),
                      n_atac_motif=sum(overlaps_motif=="overlaps motif")), 
                      by=c("tf", "paradigm", "es")]
enrDt[,enr:=motif_prop_chip/motif_prop_atac]
enrDt[,prop_atac_chip:=n_chip_motif/n_atac_motif]

enrDt <- merge(enrDt, propDt, by=c("tf"))
enrSubDt <- subset(enrDt, es==1 & paradigm=="activation")

nChIP <- ggplot(enrSubDt, aes(y="N", x=tf, fill=n_peaks))+
geom_tile(alpha=0.85)+
geom_text(aes(label=round(n_peaks, 2)), color="white",fontface="bold")+
scale_fill_viridis(option="D", end=0.95)+ # easier to see the white labels
guides(fill = guide_legend(title = "Number of ChIP-peaks",
                           label.position = "bottom"))+
scale_y_discrete(position="right")+
labs(tag="B")+
theme_bw()+
theme(axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.position="bottom")

# rename variables
propDt <- enrSubDt[,c("tf", "paradigm", "es", 
                   "motif_prop_chip", "motif_prop_atac", 
                   "motif_prop", "prop_atac_chip")]
propDt <- melt(propDt, id.vars=c("tf", "paradigm", "es"), 
               value.name="proportion")
propDt[,variable:=as.character(variable)]
propDt[, variable:=fifelse(variable=="motif_prop", 
                           "input ChIP-peaks", variable)]
propDt[, variable:=fifelse(variable=="motif_prop_chip", 
                           "ChIP-peaks overlaping ATAC-Peaks", variable)]
propDt[, variable:=fifelse(variable=="motif_prop_atac", 
                           "ATAC-peaks", variable)]
propDt[, variable:=fifelse(variable=="prop_atac_chip", 
                           "ChIP- vs ATAC-peaks", variable)]

propFullPlot <- ggplot(propDt, aes(y=variable, x=tf, fill=proportion))+
geom_tile(alpha=0.85)+
geom_text(aes(label=round(proportion, 2)), color="white",fontface="bold")+
scale_fill_viridis(option="D", end=0.95)+
guides(fill = guide_legend(title="Proportion with a motif",
                           label.position = "bottom"))+
scale_y_discrete(position="right")+
theme_bw()+
theme(axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.position="bottom")

enrPlot <- ggplot(enrSubDt, aes(y="Enrichment", x=tf, fill=enr))+
geom_tile(alpha=0.85)+
geom_text(aes(label=round(enr, 2)), color="white", fontface="bold")+
scale_fill_viridis(option="D", end=0.95)+
guides(fill = guide_legend(title = "Enrichment motifs ChIP- vs ATAC-peaks",
                           label.position = "bottom"))+
scale_y_discrete(position="right")+
theme_bw()+
theme(axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.position="bottom")

motifPlot <- nChIP / propFullPlot / enrPlot + plot_layout(heights = c(1, 4, 1))
motifPlot
```

```{r, lfc}
act <- readRDS("./data/activation.rds")
hap <- readRDS("./data/haploinsufficiency.rds")
act[,enr:=scale(enr)]
act$type <- "activation"
hap[,enr:=scale(enr)]
hap$type <- "haploinsufficiency"

lfc <- rbind(act, hap)

lfcDist <- ggplot(lfc, aes(x=enr, y=lfc))+
  facet_grid(cols=vars(type), scales="free")+
  geom_pointdensity()+
  geom_hline(yintercept=0, linetype="dashed")+
  scale_color_viridis(option="A")+
  ylab("Log fold change")+
  xlab("Enrichment over input")+
  labs(tag="A")+
  theme_bw()+
  theme(legend.position="bottom")
```

```{r, s2}
layout <- "AAAAAAACCCCCCCCCC
           AAAAAAACCCCCCCCCC
           BBBBBB#DDDDDDDDDD
           BBBBBB#DDDDDDDDDD
           BBBBBB#EEEEEEEEEE
           BBBBBB#EEEEEEEEEE"

s2 <- lfcDist+motifPlot+coRankSim+coRankGC+peakGCPlot+plot_layout(design=layout) & 
  #plot_annotation(tag_levels=list(c("A", "B", "C", "D", "E"))) &
  theme(plot.tag = element_text(face="bold", size=18),
        strip.text=element_text(size=12),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14),
        legend.justification = "center",
        legend.text = element_text(size=10),
        legend.title = element_text(size=12))

ggsave("sim_s2.png", s2, units="cm", width=60, height=40)
```

# Effect strength

Rank curves
```{r, error=TRUE}
# Import method outputs
rawFiles <- list.files("./data/sim_data_es", recursive=TRUE, full.names=TRUE)
rawFiles <- rawFiles[grepl("with_pvalues", rawFiles)]
rawFiles <- rawFiles[!grepl("_0_", rawFiles)]

res <- lapply(rawFiles, readRDS)
res <- lapply(res, as.data.table, keep.rownames=TRUE)
names(res) <- rawFiles

# organize               
res <- rbindlist(res, idcol="folder", use.names=TRUE, fill=TRUE)
res[,setting:=tstrsplit(folder, split="/", keep=4)]
res[,c("tf", "paradigm", "es"):=tstrsplit(setting, keep=1:3, split="_")]
res[,method:=tstrsplit(folder, keep=7, split="/")]
res[,method:=tstrsplit(method, keep=1, split=".", fixed=TRUE)]

# get baseline peformances (es==0)
baseLineFile <- list.files("./data/data_baseline", recursive=TRUE, full.names=TRUE)
baseLineFile <- baseLineFile[grepl("with_pvalues", baseLineFile)]
resBase <- lapply(baseLineFile, readRDS)
resBase <- lapply(resBase, as.data.table, keep.rownames=TRUE)
names(resBase) <- baseLineFile
resBase <- rbindlist(resBase, idcol="folder", use.names=TRUE, fill=TRUE)
resBase[,method:=tstrsplit(folder, keep=6, split="/")]
resBase[,method:=tstrsplit(method, keep=1, split=".", fixed=TRUE)]

params <- as.data.table(expand.grid(tf=c("CEBPB", "CTCF", "MAZ", "ZNF143"),
                                    paradigm=c("activation", "haploinsufficiency")))
resBase <- lapply(1:nrow(params), function(i){
  tf <- params[i,]$tf
  paradigm <- params[i,]$paradigm
  resBase$tf <- tf
  resBase$es <- 0
  resBase$paradigm <- paradigm
  resBase
})
resBase <- rbindlist(resBase)
res <- rbind(res, resBase, use.names=TRUE, fill=TRUE)
res <- renameMethods(res)

# calculate ranks
res[,rank:=order(p, -abs(logFC)), , by=c("tf", "paradigm", "es", "method")]
resSub <- subset(res, rn %in% c("CEBPB", "MAZ", "ZNF143", "ZN143", "CTCF"))
resSub <- subset(resSub, rn==tf | c(rn=="ZN143" & tf=="ZNF143"))
resSub[,is_sig:=padj<=0.05]
resSub <- subset(resSub, method!="msVIPER")
resSim <- resSub

# plot peformance on activation datasets
act <- ggplot(subset(resSub, paradigm=="activation"), 
              aes(x=es, y=rank, group=method)) +
geom_line()+
geom_label(subset(resSub, paradigm=="activation"), 
           mapping=aes(label=rank, x=es, y=rank, 
                       color=padj, size=is_sig), label.size=1)+
geom_text(subset(resSub, is_sig & paradigm=="activation"), 
          mapping=aes(label=rank, x=es, y=rank), color="black", 
          label.size=NA, size=4.2, fontface=2)+ # size=5
facet_grid(rows=vars(tf), cols=vars(method), scales="free")+
scale_color_viridis(option="D", direction=-1, name="adjusted p-value")+
scale_size_manual(values = c("TRUE"=4.2, "FALSE"=4.2),
                  name="significant")+
guides(size=guide_legend(override.aes = list(fontface=c(1, 2))))+ # label=c("FALSE", "TRUE")
xlab("Effect Strength")+
ylab("Rank of True TF")+
ggtitle("Activation")+
labs(tag = "C")+
scale_y_sqrt()+
theme_bw()+
theme(legend.position="bottom",
      legend.title=element_text(size=12),
      legend.text=element_text(size=10))
ggsave("rankLines_act.png", units="cm", height=28, width=35)

# plot peformance on haploinsufficiency datasets
hap <- ggplot(subset(resSub, paradigm=="haploinsufficiency"), 
              aes(x=es, y=rank, group=method)) +
geom_line()+
geom_label(subset(resSub, paradigm=="haploinsufficiency"), 
           mapping=aes(label=rank, x=es, y=rank, 
                       color=padj, size=is_sig), label.size=1)+
geom_text(subset(resSub, is_sig & paradigm=="haploinsufficiency"), 
          mapping=aes(label=rank, x=es, y=rank), color="black", 
          label.size=NA, size=4.2, fontface=2)+ # size=5
facet_grid(rows=vars(tf), cols=vars(method), scales="free")+
scale_color_viridis(option="D", direction=-1, name="adjusted p-value")+
scale_size_manual(values = c("TRUE"=4.2, "FALSE"=4.2),
                  name="significant")+
guides(size=guide_legend(override.aes = list(fontface=c(1, 2))))+ # label=c("FALSE", "TRUE")
xlab("Effect Strength")+
ylab("Rank of True TF")+
ggtitle("Haploinsufficiency")+
scale_y_sqrt()+
theme_bw()+
theme(legend.position="bottom",
      legend.title=element_text(size=12),
      legend.text=element_text(size=10))
ggsave("rankLines_haplo.png", units="cm", height=28, width=35)

es_perform <- (act / hap) + #plot_annotation(tag_levels=list(c("B", "C")))+
  plot_layout(guides = "collect") &
  theme(plot.tag = element_text(face="bold", size=18), legend.position="bottom",
        legend.key.width = unit(1, "cm"))
es_perform
ggsave("es_perform.png", units="cm", width=35, height=40)
```

```{r}
img <- readPNG("fig_main.png", native = TRUE)
ovFig <- ggplot() + 
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  labs(tag = "A")+
  theme_void() + annotation_custom(grid::rasterGrob(img), 
                    xmin = -Inf, ymin = -Inf, xmax = Inf, ymax = Inf)+
  theme(panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA),
    panel.grid = element_blank(),
    panel.border = element_blank(),
    plot.margin = unit(c(-1.25,1,-1.25, -1.25), "lines"), #c(-2, -1.25, 5, -1.25)
    panel.margin = unit(c(-1.25,1,-1.25, -1.25), "lines"),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.line = element_blank(),
    legend.position = "none",
    axis.ticks.length = unit(0, "null"),
    axis.ticks.margin = unit(0, "null"),
    legend.margin = unit(0, "null"))
ovFig

img <- my_image <- readPNG("fig_main_2.png", native = TRUE)
ovFig2 <- ggplot() + 
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  labs(tag = "B")+
  theme_void() + annotation_custom(grid::rasterGrob(img), 
                    xmin = -Inf, ymin = -Inf, xmax = Inf, ymax = Inf)+
  theme(panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA),
    panel.grid = element_blank(),
    panel.border = element_blank(),
    plot.margin = unit(c(-1.25,-1.25,-1.25,-1.25), "lines"),
    panel.margin = unit(c(-1.25,-1.25,-1.25,-1.25), "cm"),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.line = element_blank(),
    legend.position = "none",
    axis.ticks.length = unit(0, "null"),
    axis.ticks.margin = unit(0, "null"),
    legend.margin = unit(0, "null"))
ovFig2

layout <- "
AAABBB
CCCCCC
CCCCCC
"
#es_perform <- es_perform + theme(plot.margin = unit(c(-1.25,-1.25,-1.25,-1.25), "lines"))
fig1 <- ovFig + ovFig2 + es_perform + #plot_annotation(tag_levels=c("A", "B"))+
  plot_layout(guides="collect", ncol=2, nrow=2, design=layout, widths=c(1.5,1)) &
  theme(plot.tag = element_text(face="bold", size=18), 
        axis.text=element_text(size=12),
        axis.title=element_text(size=14),
        legend.title=element_text(size=14),
        legend.text=element_text(size=12),
        legend.position="bottom", 
        legend.spacing.x=unit(0.5, 'cm'),
        legend.justification = "center")
ggsave("fig_4_sim.png", fig1, units="cm", width=40, height=55)
```

Positive control
```{r}
rawFiles <- list.files("./data/sim_data_pos_control", recursive=TRUE, full.names=TRUE)
rawFiles <- rawFiles[grepl("with_pvalues", rawFiles)]
rawFiles <- rawFiles[!grepl("_0_", rawFiles)]
resPos <- lapply(rawFiles, readRDS)
resPos <- lapply(resPos, as.data.table, keep.rownames=TRUE)
names(resPos) <- rawFiles
                    
resPos <- rbindlist(resPos, idcol="folder", use.names=TRUE, fill=TRUE)
resPos[,setting:=tstrsplit(folder, split="/", keep=4)]
resPos[,c("tf", "paradigm", "es"):=tstrsplit(setting, keep=1:3, split="_")]
resPos[,method:=tstrsplit(folder, keep=7, split="/")]
resPos[,method:=tstrsplit(method, keep=1, split=".", fixed=TRUE)]

# get effect strength 0 files
baseLineFile <- list.files("./data/data_baseline", recursive=TRUE, full.names=TRUE)
baseLineFile <- baseLineFile[grepl("with_pvalues", baseLineFile)]
resBase <- lapply(baseLineFile, readRDS)
resBase <- lapply(resBase, as.data.table, keep.rownames=TRUE)
names(resBase) <- baseLineFile
resBase <- rbindlist(resBase, idcol="folder", use.names=TRUE, fill=TRUE)
resBase[,method:=tstrsplit(folder, keep=6, split="/")]
resBase[,method:=tstrsplit(method, keep=1, split=".", fixed=TRUE)]

params <- as.data.table(expand.grid(tf=c("CEBPB", "CTCF", "MAZ", "ZNF143"),
                                    paradigm=c("activation", "haploinsufficiency")))
resBase <- lapply(1:nrow(params), function(i){
  tf <- params[i,]$tf
  paradigm <- params[i,]$paradigm
  resBase$tf <- tf
  resBase$es <- 0
  resBase$paradigm <- paradigm
  resBase
})
resBase <- rbindlist(resBase)
resPos <- rbind(resPos, resBase, use.names=TRUE, fill=TRUE)
resPos <- subset(resPos, method!="msVIPER")
resPos <- renameMethods(resPos)

# relcalculate ranks
resPos[,rank:=order(p, -abs(logFC)), by=c("tf", "paradigm", "es", "method")]
resPosSub <- subset(resPos, rn %in% c("CEBPB", "MAZ", "ZNF143", "ZN143", "CTCF"))
resPosSub <- subset(resPosSub, rn==tf | c(rn=="ZN143" & tf=="ZNF143"))
resPosSub[,is_sig:=padj<=0.05]
resPosSub <- subset(resPosSub, method!="msVIPER")
resPosSub$type <- "Only motif containing ChIP-peaks"
resSub$type <- "All ChIP-peaks"

resAll <- rbind(resPosSub, resSub, fill=TRUE, check.names=TRUE)

# sizes are actually the same test it!!!  
act <- ggplot(subset(resAll, paradigm=="activation"), aes(x=es, y=rank, group=method)) +
geom_line(data=subset(resAll, type=="All ChIP-peaks" & paradigm=="activation"), color="grey")+
geom_point(data=subset(resAll, type=="All ChIP-peaks" & paradigm=="activation"), color="grey")+
geom_label_repel(data=subset(resAll, type=="All ChIP-peaks" & paradigm=="activation" & !is_sig), 
                 color="grey", aes(label=rank, size=is_sig), direction = "y", nudge_y=5, seed=43)+
geom_label_repel(data=subset(resAll, type=="All ChIP-peaks" & paradigm=="activation" & is_sig), fontface=2, 
                 color="grey", aes(label=rank, size=is_sig), direction = "y", nudge_y=5, seed=43)+
geom_line(data=subset(resAll, type=="Only motif containing ChIP-peaks" & paradigm=="activation"))+
geom_label(subset(resAll, paradigm=="activation" & type=="Only motif containing ChIP-peaks"), 
           mapping=aes(label=rank, x=es, y=rank, color=padj, size=is_sig), label.size=1)+
geom_text(subset(resAll, is_sig & paradigm=="activation" & type=="Only motif containing ChIP-peaks"), 
          mapping=aes(label=rank, x=es, y=rank), color="black", label.size=NA, size=4.2, fontface=2)+ # size=5
scale_size_manual(values=c("TRUE"=4.2, "FALSE"=4.2), name="significant")+
guides(size=guide_legend(override.aes = list(fontface=c(1, 2))))+
facet_grid(rows=vars(tf), cols=vars(method), scales="free")+
scale_color_viridis(option="D", direction=-1, name="adjusted p-value")+
xlab("Effect Strength")+
ylab("Rank of true TF")+
ggtitle("Activation")+
scale_y_sqrt()+
theme_bw()+
theme(legend.position="bottom",
      legend.title=element_text(size=12),
      legend.text=element_text(size=10))
act
ggsave("rankLines_act_pos.png", units="cm", height=28, width=35)

hap <- ggplot(subset(resAll, paradigm=="haploinsufficiency"), aes(x=es, y=rank, group=method)) +
geom_line(data=subset(resAll, type=="All ChIP-peaks" & paradigm=="haploinsufficiency"), color="grey")+
geom_point(data=subset(resAll, type=="All ChIP-peaks" & paradigm=="haploinsufficiency"), color="grey")+
geom_label_repel(data=subset(resAll, type=="All ChIP-peaks" & paradigm=="haploinsufficiency" & !is_sig), 
                 color="grey", aes(label=rank, size=is_sig), direction = "y", nudge_y=5, seed=43)+
geom_label_repel(data=subset(resAll, type=="All ChIP-peaks" & paradigm=="haploinsufficiency" & is_sig), fontface=2, 
                 color="grey", aes(label=rank, size=is_sig), direction = "y", nudge_y=5, seed=43)+
geom_line(data=subset(resAll, type=="Only motif containing ChIP-peaks" & paradigm=="haploinsufficiency"))+
geom_label(subset(resAll, paradigm=="haploinsufficiency" & type=="Only motif containing ChIP-peaks"), 
           mapping=aes(label=rank, x=es, y=rank, color=padj, size=is_sig), label.size=1)+
geom_text(subset(resAll, is_sig & paradigm=="haploinsufficiency" & type=="Only motif containing ChIP-peaks"), 
          mapping=aes(label=rank, x=es, y=rank), color="black", label.size=NA, size=4.2, fontface=2)+ # size=5
scale_size_manual(values=c("TRUE"=4.2, "FALSE"=4.2), name="significant")+
guides(size=guide_legend(override.aes = list(fontface=c(1, 2))))+
facet_grid(rows=vars(tf), cols=vars(method), scales="free")+
scale_color_viridis(option="D", direction=-1, name="adjusted p-value")+
xlab("Effect Strength")+
ylab("Rank of true TF")+
ggtitle("Haploinsufficiency")+
scale_y_sqrt()+
theme_bw()+
theme(legend.position="bottom",
      legend.title=element_text(size=12),
      legend.text=element_text(size=10))
hap
ggsave("rankLines_hap_pos.png", units="cm", height=28, width=35)

(act / hap) +plot_layout(guides = "collect") &
  theme(plot.tag = element_text(face="bold", size=18), legend.position="bottom")
ggsave("sim_s5.png", units="cm", width=35, height=40)
```

# FLD

```{r, eval=TRUE}
simfrags <- readRDS("./data/sim_data_fld/MAZ_activation_0_FALSE_group/seq_files/simfrags.rds")
simFrags <- simfrags$sim
simFrags[,fld:=fifelse(group=="group1", "NF-enriched", "Mono-enriched")]
simFrags$fld <- factor(simFrags$fld, 
                       levels=c("NF-enriched", "Mono-enriched"), ordered=TRUE)

fldDist <- ggplot(simFrags, aes(x=width, color=fld))+
geom_density(alpha=0.7, lwd=2)+
scale_color_manual(values=c("#b8db52fd", "#4d9d89fd"))+
xlab("Fragment Length")+
guides(color = guide_legend(title = "Fragment length distributions"))+
xlim(c(0,1000))+
theme_bw()+
theme(legend.title = element_blank(),
      legend.position = "bottom",
      legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(0,0,0,0))
ggsave("fl_dist.pdf", units="cm", height=8, width=14)
```

```{r}
rawFiles <- list.files("./data/sim_data_fld", recursive=TRUE, full.names=TRUE)
rawFiles <- rawFiles[grepl("with_pvalues", rawFiles)]
res <- lapply(rawFiles, readRDS)
res <- lapply(res, as.data.table, keep.rownames=TRUE)
names(res) <- rawFiles
                    
res <- rbindlist(res, idcol="folder", use.names=TRUE, fill=TRUE)
res[,setting:=tstrsplit(folder, split="/", keep=4)]
res[,c("tf", "paradigm", "es", "fld_1", "fld_2"):=tstrsplit(setting, keep=c(1:3,5,6), split="_")]
res[,fld:=paste(fld_1, fld_2, sep="_")]
res[,method:=tstrsplit(folder, keep=7, split="/")]
res[,method:=tstrsplit(method, keep=1, split=".", fixed=TRUE)]

# relcalculate ranks
res[,rank:=order(p, -abs(logFC)), by=c("tf", "paradigm", "es", "method", "fld")]
res <- subset(res, rn %in% c("CEBPB", "MAZ", "ZNF143", "ZN143", "CTCF"))
res <- subset(res, rn==tf | c(rn=="ZN143" & tf=="ZNF143"))
res[,is_sig:=padj<=0.05]
res <- renameMethods(res)

# rename FLD types
res[,fld:=fifelse(fld=="group_NA", "grouped", fld)]
res[,fld:=fifelse(fld=="mono_enriched", "All Mononucleosome enriched", fld)]
res[,fld:=fifelse(fld=="nf_enriched", "All Nucleosome-free enriched", fld)]

hap <- ggplot(subset(res, paradigm=="haploinsufficiency"), 
              aes(x=es, y=rank, group=fld, color=fld)) +
geom_line()+
geom_text_repel(aes(label=rank), 
                direction="y", size=2.5, segment.color = NA, nudge_y=10)+
geom_point(aes(size=is_sig))+
scale_size_manual(values=c(2.5, 5), name="significant")+
scale_color_manual(values=cbbPalette, name="FLD type")+
xlab("Effect Strength")+
ggtitle("Haploinsufficiency")+
facet_grid(rows=vars(tf), cols=vars(method), scales="free")+
scale_y_sqrt()+
theme_bw()+
theme(legend.position="bottom")
hap

act <- ggplot(subset(res, paradigm=="activation"), 
              aes(x=es, y=rank, group=fld, color=fld)) +
geom_line()+
geom_text_repel(aes(label=rank), direction="y", size=2.5, segment.color = NA, nudge_y=10)+
geom_point(aes(size=is_sig))+
scale_color_manual(values=cbbPalette, name="FLD type")+
scale_size_manual(values=c(2.5, 5), name="significant")+
xlab("Effect Strength")+
ggtitle("Activation")+
facet_grid(rows=vars(tf), cols=vars(method), scales="free")+
scale_y_sqrt()+
theme_bw()+
theme(legend.position="bottom")
act

(act / hap) + plot_annotation(tag_levels=list(c("A", "B")))+
  plot_layout(guides = "collect") &
  theme(plot.tag = element_text(face="bold", size=18), legend.position="bottom")
ggsave("fld_perform_lines.png", units="cm", width=35, height=20)

fldLines <- ggplot(res, aes(x=es, y=rank, group=fld, color=fld)) +
geom_line(alpha=0.5, lwd=0.7)+
geom_point(aes(size=is_sig), alpha=0.5)+
scale_color_manual(values=cbbPalette, name="FLD design")+
scale_size_manual(values=c(2.5, 5), name="significant")+
ylab("Rank of true TF")+
xlab("Effect Strength")+
facet_nested(paradigm+tf~method, scales="free")+
scale_y_continuous(trans="log1p", breaks=c(500,200,100,50,10))+
theme_bw()+
theme(legend.position="bottom", legend.justification="left")
ggsave("fld_perform_lines_alt.png", units="cm", width=35, height=20)

fldHm <- ggplot(res, aes(y=method, x=es, color=rank))+
geom_point(aes(size=is_sig))+
facet_nested(paradigm+tf~ fld, scales="free", switch="y")+
#scale_color_viridis(option="D", direction=-1, 
#                    name="Rank of true TF",
#                    end=0.9)+ # easier to see than the very bright yellow
scale_color_gradientn(trans = "sqrt",
                      breaks=c(500,200,100,50,10),
                     colours=magma(length(unique(res$rank)), 
                                     direction=-1, end=0.95), # easier to see than the very bright yellow
                     #direction=-1,
                     name="Rank of true TF")+
                     #end=0.9)+
scale_size_manual(values=c(4, 8), 
                  name="significant")+
scale_y_discrete(position="right")+
theme_bw()+
theme(legend.position="bottom",
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.key.width = unit(1, "cm"),
      legend.justification="center")

d <- data.frame(x=0, y=0, image="variations_fld.png")
ovFig1 <- ggplot(d, aes(x, y)) + 
  geom_image(aes(image=image), size=0.5,by="width")+ #, asp=1.535
  scale_size_identity()+
  theme_void()

layout <- "
AAA#CCCC
BBBBCCCC"

img <- my_image <- readPNG("variations_fld.png", native = TRUE)
ovFig1 <- ggplot() + 
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  theme_void() + annotation_custom(grid::rasterGrob(img), 
                    xmin = -Inf, ymin = -Inf, xmax = Inf, ymax = Inf)+
  theme(panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA),
    panel.grid = element_blank(),
    panel.border = element_blank(),
    plot.margin = unit(c(-1.25, 1,-1.25,-1.25), "lines"),
    panel.margin = unit(c(0,0,0,0), "lines"),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.line = element_blank(),
    legend.position = "none",
    axis.ticks.length = unit(0, "null"),
    axis.ticks.margin = unit(0, "null"),
    legend.margin = unit(0, "null"))
ovFig1

(ovFig1 + fldDist + fldHm) + 
  plot_annotation(tag_levels=list(c("A", "B", "C")))+
  plot_layout(widths = c(1.5, 1.5), heights=c(1,3), design="
              12
              33") & # design=layout
  theme(plot.tag=element_text(face="bold", size=18))
ggsave("sim_s6.png", units="cm", 
       width=30, height=30)

(ovFig1 + fldDist + fldLines) + 
  plot_annotation(tag_levels=list(c("A", "B", "C")))+
  plot_layout(widths = c(1, 1.5), heights=c(1,3), design="
              12
              33") & # design=layout
  theme(plot.tag=element_text(face="bold", size=18))
ggsave("sim_s6_alt.png", units="cm", 
       width=40, height=30)
```

# GC content variations

```{r, eval=TRUE}
gc()
simfrags <- readRDS("./data/sim_data_gc/MAZ_activation_0_FALSE_group/seq_files/simfrags.rds")
simFrags <- simfrags$sim
simFrags <- subset(simFrags, sample %in% c("group1_1", "group2_1"))
simFrags[,gc:=fifelse(group=="group1", "strong", "baseline")]
simFrags$gc <- factor(simFrags$gc, 
                       levels=c("baseline", "strong"), ordered=TRUE)

gcDist <- ggplot(simFrags, aes(x=gc_content, color=gc))+
geom_density(alpha=0.7, lwd=2)+
scale_color_manual(values=c("#fa8d24f9", "#952758ff"))+
xlab("GC content")+
guides(color = guide_legend(title = "GC design"))+
theme_bw()+
theme(legend.title = element_blank(),
      legend.position = "bottom")
gcDist
ggsave("gc_dist.pdf", units="cm", height=8, width=14)
```


```{r}
rawFiles <- list.files("./data/sim_data_gc", recursive=TRUE, full.names=TRUE)
rawFiles <- rawFiles[grepl("with_pvalues", rawFiles)]
res <- lapply(rawFiles, readRDS)
res <- lapply(res, as.data.table, keep.rownames=TRUE)
names(res) <- rawFiles
                    
res <- rbindlist(res, idcol="folder", use.names=TRUE, fill=TRUE)
res[,setting:=tstrsplit(folder, split="/", keep=4)]
res[,c("tf", "paradigm", "es", "gc_1", "gc_2"):=tstrsplit(setting, keep=c(1:3,5,6), split="_")]
res[,gc:=paste(gc_1, gc_2, sep="_")]

res[,method:=tstrsplit(folder, keep=7, split="/")]
res[,method:=tstrsplit(method, keep=1, split=".", fixed=TRUE)]

# rename GC types
res[,gc:=fifelse(gc=="all_baseline", "all baseline", gc)]
res[,gc:=fifelse(gc=="all_strong", "all strong", gc)]
res[,gc:=fifelse(gc=="group_NA", "grouped", gc)]
res[,gc:=fifelse(gc=="intermediate_1", "intermediate 1", gc)]
res[,gc:=fifelse(gc=="intermediate_2", "intermediate 2", gc)]
res$gc <- factor(res$gc, levels=c("all baseline", "all strong", 
                                  "intermediate 1", "intermediate 2",
                                  "grouped"))

# relcalculate ranks
res[,rank:=order(p, -abs(logFC)), by=c("tf", "paradigm", "es", "method", "gc")]
res <- subset(res, rn %in% c("CEBPB", "MAZ", "ZNF143", "ZN143", "CTCF"))
res <- subset(res, rn==tf | c(rn=="ZN143" & tf=="ZNF143"))
res[,is_sig:=padj<=0.05]
res <- renameMethods(res)

gcLines <- ggplot(res, aes(x=es, y=rank, group=gc, color=gc)) +
geom_line(alpha=0.5, lwd=0.7)+
geom_point(aes(size=is_sig), alpha=0.5)+
scale_color_manual(values=cbbPalette, name="GC design")+
scale_size_manual(values=c(2.5, 5), name="significant")+
xlab("Effect Strength")+
ylab("Rank of true TF")+
facet_nested(paradigm+tf~method, scales="free")+
scale_y_continuous(trans="log1p", breaks=c(500,200,100,50,10,5))+
theme_bw()+
theme(legend.position="bottom")
gcLines
ggsave("gc_perform_lines.png", units="cm", width=35, height=20)

gcHm <- ggplot(res, aes(y=method, x=es, color=rank))+
geom_point(aes(size=is_sig))+
facet_nested(paradigm+tf~ gc, scales="free", switch="y")+
scale_color_gradientn(trans = "sqrt",
                      breaks=c(500,200,100,50,10),
                      colours=viridis(length(unique(res$rank)), 
                                    direction=-1, end=0.95), # easier to see than the very bright yellow
                     #direction=-1,
                     name="Rank of true TF")+
scale_size_manual(values=c(4,8), name="significant")+
scale_y_discrete(position="right")+
theme_bw()+
theme(legend.position="bottom",
      legend.key.width = unit(1, "cm"),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.justification="center")

img <- my_image <- readPNG("variations_gc.png", native = TRUE)
ovFig1 <- ggplot() + 
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  theme_void() + annotation_custom(grid::rasterGrob(img), 
                    xmin = -Inf, ymin = -Inf, xmax = Inf, ymax = Inf)+
  theme(panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA),
    panel.grid = element_blank(),
    panel.border = element_blank(),
    plot.margin = unit(c(-1.25, 1,-1.25,-1.25), "lines"),
    panel.margin = unit(c(0,0,0,0), "lines"),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.line = element_blank(),
    legend.position = "none",
    axis.ticks.length = unit(0, "null"),
    axis.ticks.margin = unit(0, "null"),
    legend.margin = unit(0, "null"))
ovFig1

(ovFig1 + gcDist + gcHm) + plot_annotation(tag_levels=list(c("A", "B", "C")))+
  plot_layout(widths = c(1.5, 1.5), heights=c(1,3), design="
              12
              33") & # design=layout
  theme(plot.tag=element_text(face="bold", size=18))
ggsave("sim_s8.png", units="cm", 
       width=30, height=30)

(ovFig1 + gcDist + gcLines) + plot_annotation(tag_levels=list(c("A", "B", "C")))+
  plot_layout(widths = c(1, 1.5), heights=c(1,3), design="
              12
              33") & # design=layout
  theme(plot.tag=element_text(face="bold", size=18))
ggsave("sim_s7_alt.png", units="cm", 
       width=30, height=30)
```


# Overview figure 

```{r}
# results real datasets
resReal <- as.data.table(readRDS("../fullFrags/results.rds"))
resReal[,sig:=trueQ<=0.05]
resReal[,FDR:=fifelse(is.na(FDR), 0, FDR)]
resReal[,precision:=1-FDR]

# results simulated datasets
resSim <- as.data.table(readRDS("res_all_effect_strength.rds"))

resSim[,c("tf", "paradigm", "es"):=tstrsplit(dataset, split="_", keep=1:3, 
                                             type.convert=TRUE)]
resSim$method <- renameMethods(resSim$method)
resSim[,sig:=trueQ<=0.05]
resSim[,FDR:=fifelse(is.na(FDR), 0, FDR)]

# minimal effect strength at which true TF is found
suppressWarnings(resSumSim <- resSim[,.(min_es_sig=min(es[sig]),
                                        sig=sum(sig)>0), 
                                     by=.(paradigm, tf, method)])
resSumSim[,es:=fifelse(!is.finite(min_es_sig), 1, min_es_sig)]
resSumSim <- merge(resSumSim, 
                   resSim[,c("paradigm", "tf", "method", "es", "FDR")], 
                   by.x=c("paradigm","tf","method", "es"),
                   by.y=c("paradigm", "tf", "method", "es"), 
                   all.x=TRUE, 
                   all.y=FALSE)

resSumSim[,precision:=1-FDR]
resSumSim[,dataset:=paste(tf, paradigm)]

resReal <- subset(resReal, method %in% unique(resSumSim$method))

# sensitivity plots

# ordering real datasets
resRealOrder <- resReal[,.(n_sig=sum(sig)), by=dataset]
resReal$dataset <- factor(resReal$dataset,
                          levels=resRealOrder$dataset[order(-resRealOrder$n_sig)], 
                          ordered=TRUE)

# ordering simulated datasets
resSimOrder <- resSumSim[,.(n_sig=sum(sig, na.rm=TRUE)), by=dataset]
resSumSim$dataset <- factor(resSumSim$dataset,
                            levels=resSimOrder$dataset[order(-resSimOrder$n_sig)], 
                            ordered=TRUE)

# ordering methods
orderMethods <- rbind(resReal[,.(n_sig=sum(sig)), by=method],
                      resSumSim[,.(n_sig=sum(sig)), by=method])
orderMethods <- orderMethods[,.(n_sig=sum(n_sig)), by=method]
resReal$method <- factor(resReal$method,
                         levels=orderMethods$method[order(orderMethods$n_sig)],
                         ordered=TRUE)
resSumSim$method <- factor(resSumSim$method,
                         levels=orderMethods$method[order(orderMethods$n_sig)],
                         ordered=TRUE)

# real dataset summary plot
realRank <- ggplot(resReal, aes(x=dataset, y=method, color=sqrt(rank)))+
geom_point(aes(size=sig))+
scale_size_manual(values=c(8,16), name="significant")+
scale_color_gradientn(trans = "sqrt",
                      breaks=c(500,200,100,50,10),
                      colours=inferno(50), 
                      name="Rank of true TF")+  
scale_x_discrete(guide = guide_axis(n.dodge=2))+
ggtitle("Real datasets")+
labs(tag="A")+
theme_bw()+
theme(legend.position="top",
      axis.text.y = element_text(size=12, color="black"),
      #axis.text.x = element_text(size=10, color="black"),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      plot.tag=element_text(face="bold", size=18))

# simulated summary plot
resSumSim[,min_es_sig:=fifelse(!is.finite(min_es_sig), 
                               as.numeric(NA), min_es_sig)]
esSens <- ggplot(resSumSim, aes(x=dataset, y=method, color=as.factor(min_es_sig)))+
geom_point(aes(size=sig))+
scale_size_manual(values=c(8,16), name="significant")+
scale_x_discrete(guide = guide_axis(n.dodge=2))+
scale_color_brewer(palette="Purples", na.value="darkgrey", 
                   name="Minimal effect strength", direction=-1)+
ggtitle("Simulated datasets")+
guides(colour=guide_legend(override.aes = list(size=8, alpha=1, linewidth=3)))+
theme_bw()+
theme(legend.position="top",
      axis.text.x = element_text(size=12, color="black"),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(), 
      axis.ticks.y=element_blank(),
      axis.text.y = element_blank(),
      plot.tag=element_blank())

sensPlot_v1 <- realRank + esSens + 
  plot_layout(guides="collect") & 
  theme(legend.position="top",
        axis.text.x=element_blank()) & 
  labs(tag="A")


sensPlot_v2 <- realRank + esSens + 
  plot_layout(guides="collect") & 
  theme(legend.position="top",
        axis.text.x = element_text(size=12, color="black")) & 
  labs(tag="A")

# precision plots

# Results precision per effect strength 
resSimAg <- resSim[,.(FDR=mean(FDR)), by=c("method", "es")]
resSimAg[,precision:=1-FDR]

# reorder methods
precAll <- rbind(resReal[,c("dataset", "precision", "method"), with=FALSE], 
                 resSumSim[,c("dataset", "precision", "method"), with=FALSE])
precAll <- precAll[,.(mean_precision=mean(precision)), by=method]


resSim$method <- factor(resSim$method, 
                        levels=precAll$method[order(precAll$mean_precision)],
                        ordered=TRUE)
resSimAg$method <- factor(resSimAg$method, 
                          levels=precAll$method[order(precAll$mean_precision)],
                          ordered=TRUE)
resReal$method <- factor(resReal$method, 
                         levels=precAll$method[order(precAll$mean_precision)],
                         ordered=TRUE)

resReal[,precision_color:=fifelse(precision<0.9, TRUE, FALSE)]
precReal <- ggplot(resReal, aes(x=dataset, fill=precision, y=method))+
            scale_fill_gradientn(trans = "sqrt",
                        breaks=c(1.0,0.75,0.5,0.25,0.1,0),
                        colours=viridis(20), 
                        name="Precision")+
            geom_tile()+
            geom_text(aes(label=round(precision, 2), color=precision_color), 
                      fontface="bold")+
            scale_color_manual(values=c("TRUE"="white", "FALSE"="black"),
                                 guide="none")+
            scale_x_discrete(guide = guide_axis(n.dodge=2))+
            labs(tag="B")+
            theme_bw()+
            theme(axis.text.y = element_text(size=12, color="black"),
                  axis.text.x = element_text(size=12, color="black"),
                  plot.tag=element_text(face="bold", size=18))

resSimAg[,precision_color:=fifelse(precision<0.9, TRUE, FALSE)]
precSimEs <- ggplot(resSimAg, aes(x=as.factor(es), fill=precision, y=method))+
             geom_tile()+
             scale_fill_gradientn(trans = "sqrt",
                        breaks=c(1.0,0.75,0.5,0.25,0.1,0),
                        colours=viridis(20), 
                        name="Precision")+
             geom_text(aes(label=round(precision, 2), color=precision_color), 
                       fontface="bold")+
             scale_color_manual(values=c("TRUE"="white", "FALSE"="black"),
                                 guide="none")+
             xlab("Effect strength")+
             theme_bw()+
             theme(axis.text.y=element_blank(),
                   axis.text.x = element_text(size=12, color="black"),
                   plot.tag=element_blank())
precSimEs

resSumSim[,precision_color:=fifelse(precision<0.9, TRUE, FALSE)]
precSimAll <- ggplot(resSumSim, aes(x=dataset, fill=precision, y=method))+
              geom_tile()+
              scale_fill_gradientn(trans = "sqrt",
                        breaks=c(1.0,0.75,0.5,0.25,0.1,0),
                        colours=viridis(20), 
                        name="Precision")+
              geom_text(aes(label=round(precision, 2), color=precision_color), 
                        fontface="bold")+
              scale_color_manual(values=c("TRUE"="white", "FALSE"="black"),
                                 guide="none")+
              scale_x_discrete(guide = guide_axis(n.dodge=2))+
              theme_bw()+
              theme(axis.text.y=element_blank(),
                    axis.text.x = element_text(size=12, color="black"),
                    plot.tag=element_blank())
precSimAll

precPlot <- precReal+precSimEs+
            plot_layout(guides='collect')&theme(axis.title=element_blank())
precAllPlot <- precReal+precSimAll+ 
               plot_layout(guides='collect')&theme(axis.title=element_blank())

sensPlot_v2 / precPlot 
ggsave("overview_v2.png", units="cm", width=50, height=40)

sensPlot_v1 / precAllPlot
ggsave("overview_v1.png", units="cm", width=50, height=40)
```

```{r, include=FALSE, error=TRUE, eval=FALSE}
relAUCplot2 <- function(res, doDraw=TRUE, column_title="Datasets", 
                        column_order=NULL, row_order=NULL, ..., 
                        type=c("propOfMax","MAD","relAUC"), cellLabelFontsize=8,
                        datasetInfo=data.frame(
                           type=sapply(getDatasets(), FUN=function(x) x$type))){
  
  res <- as.data.table(res)
  res <- copy(res)
  setorder(res, tf, effect_strength)
  res[,propAUC:=AUC/max(AUC, na.rm=TRUE), by=.(tf, paradigm)]
  
  m1 <- data.table::dcast(res, paradigm+method~effect_strength+tf, value.var="relAUC") 
  m <- data.table::dcast(res, paradigm+method~effect_strength+tf, value.var="propAUC") 
  rankMat <- data.table::dcast(res, paradigm+method~effect_strength+tf, value.var="rank")
  methods <- rankMat$method
  paradigm <- rankMat$paradigm
  
  rankMat$method <- NULL
  rankMat$paradigm <- NULL
  m1$method <- NULL
  m1$paradigm <- NULL
  m$method <- NULL
  m$paradigm <- NULL
  
  rankMat <- as.matrix(rankMat)
  rankMat <- sqrt(rankMat)
  m <- as.matrix(m)
  m1 <- as.matrix(m1)
  m <- apply(m, 2, as.numeric)
  m1 <- apply(m1, 2, as.numeric)

  rownames(rankMat) <- rownames(m) <- rownames(m1) <- paste(methods, paradigm, sep="_")
  
  ancols <- list(type=c(deletion="darkorange3", dTag="black", ligand="darkslateblue"))
  
  colAnnot <- data.table(dataset=colnames(rankMat))
  colAnnot[,c("Effect strength", "TF"):=tstrsplit(dataset, split="_", keep=1:2)]
  colEs <- brewer.pal(5, "Blues")
  names(colEs) <- c(0, 0.25, 0.5, 1, 3)
  tfCols <- c("darkorange3", "black", "darkslateblue", "darkolivegreen")
  names(tfCols) <- c("CEBPB", "CTCF", "MAZ", "ZNF143")
  
  rankMat <- rankMat[,colnames(rankMat)[order(colAnnot$TF)]]
  m <- m[,colnames(m)[order(colAnnot$TF)]]
  m1 <- m1[,colnames(m1)[order(colAnnot$TF)]]
  setorder(colAnnot, TF)
  
  #setorder(colAnnot, tf, effect_strength)
  colan <- HeatmapAnnotation(df=as.data.frame(colAnnot[,c("TF", "Effect strength"), with=FALSE]),
                             col=list("TF"=tfCols,
                                      "Effect strength"=colEs), 
                             show_annotation_name=FALSE)

  rann <- getMethodAnno(methods)
  rowAnnot <- data.table(LFCbased=rann$df$LFCbased,
                         family=rann$df$family,
                         paradigm=paradigm)
  rownames(rowAnnot) <- rownames(rankMat)
  
  rowann <- rowAnnotation(df=rowAnnot, col=rann$col,
                          show_legend=colnames(rann$df)=="family")
  ro <- rownames(rankMat)[order(rowMeans(rankMat, na.rm=TRUE))]
  h <- ComplexHeatmap::Heatmap(m, cluster_rows=FALSE, cluster_columns=FALSE,
          cell_fun=function(j, i, x, y, width, height, fill) {
        v <- gsub("^0","",round(m1[i,j],2))
        if(is.na(v)) v <- "."
        if(v=="") v <- "0"
        if(v=="NaN") v <- "NA"
        grid.text(v, x, y, gp=gpar(fontsize=ifelse(is.na(m1[i,j]),6,
                                                   cellLabelFontsize),
                                   col=ifelse(m[i,j]<0.5,"lightgrey","black")))
      },
     col=viridisLite::magma(100), 
     name="Relative\nnetwork AUC",
     column_title=column_title, 
     column_labels=colAnnot$`Effect strength`,
     row_labels=methods,
     row_order=ro, 
     column_split=colAnnot$TF,
     row_split=rowAnnot$paradigm,
     column_order=colnames(rankMat)[order(colAnnot$TF, colAnnot$`Effect strength`)],
     row_names_side="left", top_annotation=colan)
  
  if(!doDraw) return(h)
  draw(h, merge=TRUE)
}

library(RColorBrewer)
library(ComplexHeatmap)
rankHeatmap2 <- function(res, rankBreaks=c(1,10,30,75,150,300,600), ..., 
                         column_title="Datasets", doDraw=TRUE, rowann=NULL,
                         datasetInfo=data.frame(type=sapply(getDatasets(), FUN=function(x) x$type)),
                         cellLabelFontsize=8,
                         transform=TRUE,
                         value.var="rank"){
  setorder(res, tf, effect_strength)
  
  rankMat <- data.table::dcast(res, paradigm+method~effect_strength+tf, value.var=value.var)
  methods <- rankMat$method
  paradigm <- rankMat$paradigm
  rankMat$method <- NULL
  rankMat$paradigm <- NULL
  
  rankMat <- as.matrix(rankMat)
  if(transform) rankMat <- sqrt(rankMat)
  rownames(rankMat) <- paste(methods, paradigm, sep="_")
  
  ancols <- list(type=c(deletion="darkorange3", dTag="black", ligand="darkslateblue"))
  
  colAnnot <- data.table(dataset=colnames(rankMat))
  colAnnot[,c("Effect strength", "TF"):=tstrsplit(dataset, split="_", keep=1:2)]
  colEs <- brewer.pal(5, "Blues")
  names(colEs) <- c(0, 0.25, 0.5, 1, 3)
  tfCols <- c("darkorange3", "black", "darkslateblue", "darkolivegreen")
  names(tfCols) <- c("CEBPB", "CTCF", "MAZ", "ZNF143")
  
  rankMat <- rankMat[,colnames(rankMat)[order(colAnnot$TF)]]
  setorder(colAnnot, TF)
  
  #setorder(colAnnot, tf, effect_strength)
  colan <- HeatmapAnnotation(df=as.data.frame(colAnnot[,c("TF", "Effect strength"), with=FALSE]),
                             col=list("TF"=tfCols,
                                      "Effect strength"=colEs), 
                             show_annotation_name=FALSE)

  bdist <- log10(rankBreaks[-1]-rankBreaks[-length(rankBreaks)])
  
  rann <- getMethodAnno(methods)
  rowAnnot <- data.table(LFCbased=rann$df$LFCbased,
                         family=rann$df$family,
                         paradigm=paradigm)
  rownames(rowAnnot) <- rownames(rankMat)
  
  rowann <- rowAnnotation(df=rowAnnot, col=rann$col,
                          show_legend=colnames(rann$df)=="family")
  ro <- rownames(rankMat)[order(rowMeans(rankMat, na.rm=TRUE))]

  
  h <- ComplexHeatmap::Heatmap(rankMat, cluster_rows=FALSE, cluster_columns=FALSE,
          cell_fun=function(j, i, x, y, width, height, fill) {
            grid.text(sprintf("%1.0f", rankMat[i, j]^2), x, y,
                      gp = gpar(fontsize=ifelse(is.na(rankMat[i, j]),6,
                                                cellLabelFontsize)))
          },
     col=viridisLite::viridis(100, direction=-1), name="Rank of\ntrue TF",
     column_title=column_title, 
     column_labels=colAnnot$`Effect strength`,
     row_labels=methods,
     row_order=ro, 
     column_split=colAnnot$TF,
     row_split=rowAnnot$paradigm,
     column_order=colnames(rankMat)[order(colAnnot$TF, colAnnot$`Effect strength`)], 
     left_annotation=rowann, row_names_side="left", top_annotation=colan,
     heatmap_legend_param=list(at=rev(sqrt(rankBreaks)),
                               labels=rev(c("top",rankBreaks[-1])),
                               break_dist=rev(bdist), legend_height=unit(3.5, "cm"),
                               labels_gp=gpar(fontsize=9)))
  
  if(!doDraw) return(h)
  draw(h, merge=TRUE)
}
```

```{r, eval=TRUE, error=TRUE, eval=FALSE}
res <- readRDS("res_all_effect_strength.rds")
res <- as.data.table(res)
res[,c("tf","paradigm","effect_strength"):=tstrsplit(dataset, split="_", keep=c(1,2,3))]

res <- renameMethods(as.data.frame(res))
h1 <- rankHeatmap2(copy(res), doDraw=FALSE, column_title="Rank of true TF", row_names_gp=gpar(fontsize=10))
h2 <- relAUCplot2(copy(res), doDraw=FALSE, column_title="Network Score")
h <- grid.grabExpr(draw(h1 + h2, merge=TRUE))
fig <- cowplot::plot_grid(h)
fig
pdf("sim_s8.pdf", width=15, height=10)
fig
dev.off()

h <- grid.grabExpr(draw(h1))
fig <- cowplot::plot_grid(h)
pdf("sim_s8_1.pdf", width=10, height=10)
fig
dev.off()
```

```{r, session info}
print(sessionInfo())
```

